### ISSUE TITLE
Media Button shows in Game Details even when Trailers is disabled

### ISSUE THREAD

**Issue by akumenon** [davidkgriggs/Playnite-Deck#1]
First off, thank you for making this! I spoke to you briefly on the Playnite Discord regarding this: As of now, unchecking Trailers in DKG Theme Modifier, applying, and saving still shows the Media button in Game Details when it shouldn't. These are the extensions and versions I'm using:

Playnite 9.14
DKG Theme Modifier 2.3.3
Extra Metadata Loader 1.29
Extra Metadata Fullscreen Mode Helper 2.8
Playnite Deck 1.0.0

Please let me know if you need any more information.

Thank you and best regards.

**Comment by davidkgriggs** [comment]
Fixed in v1.0.1, no ETA on release.
