### ISSUE TITLE
[BUG] Games disappear during menu

### ISSUE THREAD

**Issue by evorm** [davidkgriggs/Playnite-Deck#10]
![image](https://user-images.githubusercontent.com/22216296/203398359-a0de69e1-6921-479e-aa7e-6e6fdcc41b4b.png)

![image](https://user-images.githubusercontent.com/22216296/203398491-eb7557fb-d721-4d42-abf4-9cefaf8d69eb.png)

The grid of games does not move to the right, but disappears altogether when accessing the menu. I preferred a more compact menu from the previous version if there are not going to be many options in it over having it look more authentic to the deck. Another request would be to tie the menu to a keybind but I am not sure if that even works that way with themes.

**Comment by evorm** [comment]
I would like to update that although the screenshot shows the posters in the 3:4 ratio I have also tried them with Steam's 2:3 ratio and they still disappear.

**Comment by davidkgriggs** [comment]
This is not a bug. It is a byproduct of themes not having full control of focus, the focus would lock onto the games when trying to navigate the menu if it did not disappear, so it has to disappear for now unless I find a way around it in the future. Sorry. If you prefer the previous menu you can always use the version before this.
