### ISSUE TITLE
Remove "NEW TO LIBRARY" label completely

### ISSUE THREAD

**Issue by C-Dub87** [davidkgriggs/Playnite-Deck#3]
The "NEW TO LIBRARY" label is distracting and doesn't function in the same way as it does on Steam, where it is applied to games you've just bought and vanishes after a while. You need to actually play the game on Playnite to make it go away.

Can we just disable it instead? I find it only obscures covers and is distracting.

Maybe let us switch it off in DKG Theme Modifier?

**Comment by davidkgriggs** [comment]
Option added, will be available in v1.0.1 of the theme and v2.3.4 of DKG Theme modifier. No ETA on release.

**Comment by hlebushekhub** [comment]
Is it working? I still get Pick another even with option being turned off in DKG
