### ISSUE TITLE
[Feature Request] Smooth scrolling animation in lists

### ISSUE THREAD

**Issue by jackgllghr** [davidkgriggs/Playnite-Deck#5]
Hi, love the theme, great work! 

The main thing I'd like to see in it is smooth scrolling in the horizontal list and the vertical scrolling grid view, I think it'd certainly elevate this theme and your others.

I'm not overly familiar with WPF, but I may fork this and give it a go if you're busy, any tips would be great.

**Comment by davidkgriggs** [comment]
It's a feature that needs to be added to playnite and not to the theme itself. The themes don't have that much input into controls. I believe Playnite 10 will have smooth scrolling.

**Comment by jackgllghr** [comment]
Thanks for the reply, looking forward to it, and kudos again on the themes 👍
