### ISSUE TITLE
Media controls shown in game details even if Extra Metadata Loader's video player is disabled.

### ISSUE THREAD

**Issue by akumenon** [davidkgriggs/Playnite-Deck#7]
This was a bug in a previous version that was fixed but has since returned in the newest version.

Details:
Playnite Deck 1.1.0
Extra Metadata Loader 1.47
Extra Metadata Fullscreen mode Helper 2.11
Playnite 9.16
Windows 10 Pro x64.

Please let me know if there is any other info I should add. 

Thank you and best regards.

**Comment by davidkgriggs** [comment]
Fixed in v1.1.1
